# Gradle
org.gradle.jvmargs=-Xmx2G -XX\:+UseParallelGC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# Mod
mod_id=durability_enhanced
mod_name=DurabilityEnhanced
mod_license=MIT
mod_version=0.1
mod_group_id=com.forgestove.durability_enhanced
mod_authors=ForgeStove
mod_display_url=https://modrinth.com/project/durability-enhanced
mod_issue_url=https://github.com/ForgeStove/DurabilityEnhanced/issues
mod_description=A mod that removed the accumulate penalties for anvil repair items
# Version
minecraft_version=1.21.4
loader_version=21.4.124
parchment_version=+
cloth_config_version=17.0.144
# Loader
loader=neoforge
upper_loader=NeoForge
